import { TriviaQuestion } from '@/types/game'

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'q001',
    question: 'Which architecture do GPT models use as their foundation?',
    options: ['RNN', 'Transformer', 'CNN', 'LSTM'],
    correctIndex: 1,
    explanation: 'GPT models use the Transformer architecture, introduced in "Attention Is All You Need" (2017) by Google Brain.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q002',
    question: 'What does "LLM" stand for in AI?',
    options: ['Large Language Model', 'Linear Learning Machine', 'Layered Logic Module', 'Lightweight Language Manager'],
    correctIndex: 0,
    explanation: 'LLM stands for Large Language Model — AI systems trained on massive text datasets like GPT-4, Claude, and Gemini.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q003',
    question: 'Which company created ChatGPT?',
    options: ['Google', 'Meta', 'OpenAI', 'Anthropic'],
    correctIndex: 2,
    explanation: 'OpenAI created ChatGPT, which launched in November 2022 and became one of the fastest-growing apps in history.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q004',
    question: 'What is "prompt engineering"?',
    options: [
      'Building physical AI hardware',
      'The art of crafting effective inputs to get better AI outputs',
      'Training AI models from scratch',
      'Debugging AI code errors',
    ],
    correctIndex: 1,
    explanation: 'Prompt engineering is the practice of designing and optimizing text prompts to guide AI models toward desired outputs.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q005',
    question: 'What is the "hallucination" problem in LLMs?',
    options: [
      'When AI sees visual patterns that aren\'t there',
      'When AI generates confidently stated but false information',
      'When AI models run too slowly',
      'When AI refuses to answer questions',
    ],
    correctIndex: 1,
    explanation: 'Hallucination refers to when LLMs generate plausible-sounding but factually incorrect information with apparent confidence.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q006',
    question: 'Which AI model was developed by Anthropic?',
    options: ['GPT-4', 'Gemini', 'Claude', 'Grok'],
    correctIndex: 2,
    explanation: 'Claude is Anthropic\'s AI assistant, known for its focus on safety and helpfulness. Anthropic was founded by former OpenAI researchers.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q007',
    question: 'What does "fine-tuning" an AI model mean?',
    options: [
      'Making an AI faster',
      'Adjusting hardware settings',
      'Further training a pre-trained model on specific data',
      'Removing bugs from AI code',
    ],
    correctIndex: 2,
    explanation: 'Fine-tuning involves taking a pre-trained model and training it further on a smaller, task-specific dataset to improve performance for that task.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q008',
    question: 'What year was the original Transformer paper "Attention Is All You Need" published?',
    options: ['2015', '2016', '2017', '2018'],
    correctIndex: 2,
    explanation: 'The landmark paper "Attention Is All You Need" was published in 2017 by researchers at Google Brain and Google Research.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 'q009',
    question: 'What is RAG in the context of AI?',
    options: [
      'Random Activation Generator',
      'Retrieval-Augmented Generation',
      'Recursive Attention Gradient',
      'Real-time AI Gateway',
    ],
    correctIndex: 1,
    explanation: 'RAG (Retrieval-Augmented Generation) combines language model generation with information retrieval to provide more accurate, up-to-date responses.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q010',
    question: 'Which AI tool generates images from text descriptions?',
    options: ['ChatGPT', 'DALL-E', 'Whisper', 'Copilot Code'],
    correctIndex: 1,
    explanation: 'DALL-E (by OpenAI) is a text-to-image AI model. Other popular image generators include Midjourney, Stable Diffusion, and Firefly.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q011',
    question: 'What is the "context window" of an LLM?',
    options: [
      'The visual interface of the AI',
      'The maximum amount of text the model can process at once',
      'The training data size',
      'The number of AI parameters',
    ],
    correctIndex: 1,
    explanation: 'The context window is the maximum number of tokens (roughly words/characters) an LLM can process in a single interaction — crucial for long documents.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q012',
    question: 'What does "GPU" stand for and why is it important for AI?',
    options: [
      'General Processing Unit — handles all computing',
      'Graphics Processing Unit — accelerates parallel computations for AI training',
      'Gigabyte Processing Unit — stores AI data',
      'Global Program Utility — manages AI software',
    ],
    correctIndex: 1,
    explanation: 'GPUs (Graphics Processing Units) are crucial for AI because they excel at parallel computation, dramatically speeding up matrix operations used in neural networks.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q013',
    question: 'Which company owns DeepMind?',
    options: ['Meta', 'Microsoft', 'Apple', 'Google/Alphabet'],
    correctIndex: 3,
    explanation: 'DeepMind was acquired by Google in 2014 and operates as part of Alphabet. They created AlphaGo, AlphaFold, and Gemini.',
    difficulty: 'medium',
    category: 'companies',
  },
  {
    id: 'q014',
    question: 'What is "tokenization" in NLP?',
    options: [
      'Encrypting AI responses',
      'Breaking text into smaller units (words/subwords) for processing',
      'Converting AI outputs to tokens for payment',
      'Storing AI models as blockchain tokens',
    ],
    correctIndex: 1,
    explanation: 'Tokenization is the process of splitting text into tokens (words, subwords, or characters) that the model can process numerically.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q015',
    question: 'What was the first AI to defeat a world champion at Go?',
    options: ['Deep Blue', 'Watson', 'AlphaGo', 'AlphaZero'],
    correctIndex: 2,
    explanation: 'AlphaGo by DeepMind defeated world Go champion Lee Sedol in 2016, marking a milestone in AI since Go has more board configurations than atoms in the universe.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 'q016',
    question: 'What is "RLHF" used for in training LLMs?',
    options: [
      'Reinforcement Learning from Human Feedback — aligning AI to human preferences',
      'Recursive Learning from Historical Files — training on old data',
      'Random Loss from Hidden Features — reducing model size',
      'Real-time Learning from Hardware Feedback — optimizing speed',
    ],
    correctIndex: 0,
    explanation: 'RLHF (Reinforcement Learning from Human Feedback) is the technique used to fine-tune models like ChatGPT to be helpful, harmless, and honest.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q017',
    question: 'What is Stable Diffusion?',
    options: [
      'A network stability protocol for AI servers',
      'An open-source text-to-image AI model',
      'A Microsoft AI coding assistant',
      'A method for stabilizing AI training',
    ],
    correctIndex: 1,
    explanation: 'Stable Diffusion is an open-source text-to-image model developed by Stability AI, notable for being free and runnable locally.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q018',
    question: 'What does "parameter" mean in the context of AI models?',
    options: [
      'The speed of the model',
      'The learnable weights in the neural network',
      'The input size limit',
      'The number of training examples',
    ],
    correctIndex: 1,
    explanation: 'Parameters are the learnable weights in a neural network. GPT-4 has ~1.8 trillion parameters. More parameters generally means more capability but also more compute.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q019',
    question: 'Which AI completed the Turing Test according to Alan Turing\'s original definition?',
    options: [
      'GPT-4',
      'ELIZA',
      'No AI has definitively passed it',
      'IBM Watson',
    ],
    correctIndex: 2,
    explanation: 'No AI has definitively and universally passed the Turing Test. While some AI in limited contexts has fooled judges, the test remains philosophically contested.',
    difficulty: 'hard',
    category: 'history',
  },
  {
    id: 'q020',
    question: 'What is "zero-shot learning" in AI?',
    options: [
      'Training a model with no data',
      'An AI performing tasks without any task-specific examples',
      'Achieving 0% error rate during training',
      'An AI that takes zero time to respond',
    ],
    correctIndex: 1,
    explanation: 'Zero-shot learning is when an AI performs a task it hasn\'t seen examples of, relying on its general knowledge and reasoning from its training.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q021',
    question: 'What is Microsoft Copilot?',
    options: [
      'A flight simulator AI',
      'Microsoft\'s AI assistant integrated into Microsoft 365 products',
      'An autonomous coding robot',
      'A cloud server management tool',
    ],
    correctIndex: 1,
    explanation: 'Microsoft Copilot is an AI assistant powered by OpenAI models, integrated into Microsoft 365 (Word, Excel, Teams) and Windows.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q022',
    question: 'What is the difference between AI and Machine Learning?',
    options: [
      'They are the same thing',
      'ML is a subset of AI that learns from data',
      'AI is a subset of ML',
      'ML only works with images, AI works with text',
    ],
    correctIndex: 1,
    explanation: 'AI is the broad field of making machines intelligent. Machine Learning is a subset of AI focused on systems that learn from data without explicit programming.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q023',
    question: 'What is "overfitting" in machine learning?',
    options: [
      'Training a model too long',
      'When a model learns training data too well and performs poorly on new data',
      'Having too many layers in a neural network',
      'Using too much GPU memory',
    ],
    correctIndex: 1,
    explanation: 'Overfitting occurs when a model memorizes training data rather than learning general patterns, causing poor performance on unseen data.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q024',
    question: 'Which company created the Gemini AI model?',
    options: ['OpenAI', 'Meta', 'Google', 'Mistral'],
    correctIndex: 2,
    explanation: 'Gemini is Google\'s flagship AI model, developed by Google DeepMind. It replaced the Bard chatbot and competes with GPT-4 and Claude.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q025',
    question: 'What does "multimodal AI" mean?',
    options: [
      'AI that runs on multiple servers',
      'AI that can process multiple types of data (text, images, audio)',
      'AI with multiple personalities',
      'AI that uses multiple programming languages',
    ],
    correctIndex: 1,
    explanation: 'Multimodal AI can understand and generate multiple modalities — like GPT-4V which processes both text and images, or Gemini Ultra which handles text, images, audio, and video.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q026',
    question: 'What is "attention mechanism" in transformers?',
    options: [
      'A way to make AI pay attention to user prompts',
      'A mechanism that lets models weigh the importance of different parts of input',
      'A monitoring system for AI outputs',
      'A technique to speed up model inference',
    ],
    correctIndex: 1,
    explanation: 'The attention mechanism allows transformers to consider how relevant each part of the input is to every other part, enabling better contextual understanding.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q027',
    question: 'Which open-source AI model family was released by Meta?',
    options: ['Claude', 'Gemma', 'Llama', 'Mistral'],
    correctIndex: 2,
    explanation: 'Meta released the Llama (Large Language Model Meta AI) family of open-source models, including Llama 2 and Llama 3, which can be run locally.',
    difficulty: 'easy',
    category: 'models',
  },
  {
    id: 'q028',
    question: 'What is "AI alignment"?',
    options: [
      'Making sure AI text is left-aligned',
      'Training AI to follow human values and intentions safely',
      'Synchronizing multiple AI systems',
      'Aligning AI training data with real-world distributions',
    ],
    correctIndex: 1,
    explanation: 'AI alignment is the challenge of ensuring AI systems behave in accordance with human values, intentions, and safety — a key focus area of Anthropic and OpenAI.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q029',
    question: 'What was IBM Watson famous for?',
    options: [
      'Generating images',
      'Writing code autonomously',
      'Defeating humans at Jeopardy! in 2011',
      'Creating the first chatbot',
    ],
    correctIndex: 2,
    explanation: 'IBM Watson famously defeated Jeopardy! champions Ken Jennings and Brad Rutter in 2011, showcasing AI\'s ability to understand natural language questions.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 'q030',
    question: 'What is "vector embedding" in AI?',
    options: [
      'Storing AI in a vector graphics format',
      'Converting text/data into numerical representations that capture meaning',
      'Embedding watermarks into AI outputs',
      'A technique for compressing AI models',
    ],
    correctIndex: 1,
    explanation: 'Vector embeddings are numerical representations of data (text, images) where similar items are closer in the vector space — crucial for semantic search and RAG.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q031',
    question: 'What AI tool helps developers write code?',
    options: ['DALL-E', 'GitHub Copilot', 'Whisper', 'Midjourney'],
    correctIndex: 1,
    explanation: 'GitHub Copilot, powered by OpenAI Codex, suggests code completions, functions, and entire blocks as you type in your editor.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q032',
    question: 'What is "diffusion" in AI image generation?',
    options: [
      'Distributing images across servers',
      'A process of gradually adding then removing noise to generate images',
      'Making images blurry for privacy',
      'A type of image compression algorithm',
    ],
    correctIndex: 1,
    explanation: 'Diffusion models learn to generate images by learning to reverse a process of gradually adding noise to images — the basis for Stable Diffusion and DALL-E 3.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q033',
    question: 'What is "AGI"?',
    options: [
      'Advanced Graphics Intelligence',
      'Artificial General Intelligence — AI that matches human-level reasoning across all tasks',
      'Automated Generation Interface',
      'Adaptive GPU Integration',
    ],
    correctIndex: 1,
    explanation: 'AGI (Artificial General Intelligence) refers to hypothetical AI that can perform any intellectual task a human can. Most experts believe we haven\'t achieved it yet.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q034',
    question: 'What is Hugging Face?',
    options: [
      'A social network for AI researchers',
      'A robot that simulates human emotions',
      'An open-source AI platform for sharing models, datasets, and demos',
      'A children\'s AI educational app',
    ],
    correctIndex: 2,
    explanation: 'Hugging Face is the "GitHub of AI" — a platform where researchers and developers share pre-trained models, datasets, and ML demos (Spaces).',
    difficulty: 'medium',
    category: 'tools',
  },
  {
    id: 'q035',
    question: 'What is "neural network" inspired by?',
    options: [
      'Computer circuit boards',
      'The human brain\'s structure of interconnected neurons',
      'Internet network topology',
      'Quantum physics',
    ],
    correctIndex: 1,
    explanation: 'Artificial neural networks are inspired by the biological neural networks in the human brain, using interconnected nodes that pass signals and learn.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q036',
    question: 'What milestone did AlphaFold achieve?',
    options: [
      'Defeated the world chess champion',
      'Solved the protein folding problem for nearly all known proteins',
      'Passed the Turing Test',
      'Wrote a novel indistinguishable from human writing',
    ],
    correctIndex: 1,
    explanation: 'AlphaFold by DeepMind predicted the 3D structure of nearly all 200 million known proteins with high accuracy, revolutionizing biology and drug discovery.',
    difficulty: 'hard',
    category: 'history',
  },
  {
    id: 'q037',
    question: 'What is "temperature" in LLM generation?',
    options: [
      'The heat generated by GPU during inference',
      'A parameter controlling randomness — higher = more creative, lower = more deterministic',
      'The processing speed of the model',
      'The length of generated text',
    ],
    correctIndex: 1,
    explanation: 'Temperature controls output randomness. Temperature 0 gives deterministic, repetitive outputs. Temperature 1+ gives more varied, creative (and sometimes incoherent) outputs.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q038',
    question: 'Which French AI company created the Mistral models?',
    options: ['BNP AI Labs', 'Mistral AI', 'Ariane Intelligence', 'EDF Tech'],
    correctIndex: 1,
    explanation: 'Mistral AI is a French startup that released highly capable open-source models (Mistral 7B, Mixtral 8x7B) competitive with much larger models.',
    difficulty: 'medium',
    category: 'companies',
  },
  {
    id: 'q039',
    question: 'What does "inference" mean in AI deployment?',
    options: [
      'Training the AI model',
      'Using a trained model to make predictions on new data',
      'Evaluating model accuracy',
      'Storing the model on servers',
    ],
    correctIndex: 1,
    explanation: 'Inference is when you use an already-trained model to generate outputs (predictions) from new inputs — distinct from training, which is the learning phase.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q040',
    question: 'What was the first publicly available chatbot?',
    options: ['Siri', 'ELIZA', 'Alexa', 'Cortana'],
    correctIndex: 1,
    explanation: 'ELIZA was created at MIT in 1966 by Joseph Weizenbaum. It simulated conversation using pattern matching and is considered one of the first chatbots.',
    difficulty: 'hard',
    category: 'history',
  },
  {
    id: 'q041',
    question: 'What is "few-shot learning"?',
    options: [
      'Training AI with very few GPU shots (iterations)',
      'Providing a small number of examples in the prompt to guide AI output',
      'A method that uses only 3-5 training samples total',
      'An efficient inference technique',
    ],
    correctIndex: 1,
    explanation: 'Few-shot learning involves giving the model a few examples in the prompt (e.g., 3-5 input-output pairs) to help it understand the desired output format.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q042',
    question: 'What is OpenRouter?',
    options: [
      'A router for open-source software networks',
      'An AI model from OpenAI',
      'A platform that provides unified access to many AI models via one API',
      'A tool for routing AI traffic across data centers',
    ],
    correctIndex: 2,
    explanation: 'OpenRouter is an API gateway that gives developers access to hundreds of AI models (GPT-4, Claude, Llama, etc.) through a single unified API.',
    difficulty: 'medium',
    category: 'tools',
  },
  {
    id: 'q043',
    question: 'What is "chain-of-thought prompting"?',
    options: [
      'Linking multiple chatbots together',
      'A technique where AI shows step-by-step reasoning before answering',
      'Chaining multiple API calls for complex tasks',
      'A blockchain-based AI verification method',
    ],
    correctIndex: 1,
    explanation: 'Chain-of-thought prompting (by Google Brain) encourages LLMs to reason step-by-step before giving a final answer, significantly improving performance on reasoning tasks.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q044',
    question: 'What is Midjourney?',
    options: [
      'A journey planning AI app',
      'An AI music generator',
      'An AI image generation tool accessible via Discord',
      'A mid-level AI chip for consumer GPUs',
    ],
    correctIndex: 2,
    explanation: 'Midjourney is a popular AI image generator known for high-quality, artistic outputs, accessible through a Discord bot interface.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q045',
    question: 'What is "reinforcement learning"?',
    options: [
      'Strengthening neural network layers',
      'Training AI through rewards and penalties based on its actions',
      'Re-training models to fix errors',
      'Adding more data to strengthen model knowledge',
    ],
    correctIndex: 1,
    explanation: 'Reinforcement Learning trains AI agents by rewarding good actions and penalizing bad ones, used in game-playing AI, robotics, and RLHF for LLMs.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q046',
    question: 'What company created the Claude AI model?',
    options: ['OpenAI', 'Google', 'Meta', 'Anthropic'],
    correctIndex: 3,
    explanation: 'Claude is created by Anthropic, an AI safety company founded in 2021 by former OpenAI researchers including Dario Amodei and Daniela Amodei.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q047',
    question: 'What is "Grok"?',
    options: [
      'A data analysis tool by Splunk',
      'An AI assistant created by xAI (Elon Musk\'s company)',
      'A German AI research institute',
      'An open-source LLM by Apache',
    ],
    correctIndex: 1,
    explanation: 'Grok is an AI assistant developed by xAI, Elon Musk\'s AI company, trained with access to real-time X (Twitter) data.',
    difficulty: 'medium',
    category: 'companies',
  },
  {
    id: 'q048',
    question: 'What is a "foundation model"?',
    options: [
      'The first AI model ever trained',
      'A large model trained on broad data that can be adapted to many tasks',
      'The base infrastructure running AI models',
      'An AI model for architecture/construction planning',
    ],
    correctIndex: 1,
    explanation: 'Foundation models are large AI models (like GPT-4, BERT) trained on vast datasets that serve as a base for fine-tuning on specific tasks — coined by Stanford researchers.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q049',
    question: 'What does "Whisper" do?',
    options: [
      'Generates whisper-quiet AI responses',
      'Converts speech to text (automatic speech recognition)',
      'Creates AI-generated audio/music',
      'A secret messaging AI tool',
    ],
    correctIndex: 1,
    explanation: 'Whisper is OpenAI\'s automatic speech recognition (ASR) model that transcribes and translates audio in 97 languages with high accuracy.',
    difficulty: 'medium',
    category: 'tools',
  },
  {
    id: 'q050',
    question: 'What is "model quantization" in AI?',
    options: [
      'Measuring model performance with quantum computers',
      'Reducing model size by using lower precision numbers, enabling local deployment',
      'Counting the number of parameters in a model',
      'A technique to split models across multiple GPUs',
    ],
    correctIndex: 1,
    explanation: 'Quantization reduces model precision (e.g., from 32-bit to 4-bit numbers), dramatically reducing file size and compute requirements — enabling local AI like llama.cpp.',
    difficulty: 'hard',
    category: 'concepts',
  },

  // ─── IMAGE AI ───────────────────────────────────────────────
  {
    id: 'img001',
    question: 'Which AI model created by OpenAI generates images from text prompts?',
    options: ['Stable Diffusion', 'Midjourney', 'DALL-E', 'Firefly'],
    correctIndex: 2,
    explanation: 'DALL-E (named after Salvador Dalí and the robot WALL-E) is OpenAI\'s text-to-image model. DALL-E 3 is integrated into ChatGPT Plus.',
    difficulty: 'easy',
    category: 'image_ai',
  },
  {
    id: 'img002',
    question: 'What does "diffusion" mean in the context of Stable Diffusion?',
    options: [
      'The model spreads across multiple GPUs',
      'The model learns by adding and removing noise from images',
      'Images are split into smaller tiles for processing',
      'The model diffuses text tokens into pixel values directly',
    ],
    correctIndex: 1,
    explanation: 'Diffusion models work by learning to reverse a process of adding noise to images. They start from pure noise and "denoise" step by step to generate the final image.',
    difficulty: 'medium',
    category: 'image_ai',
  },
  {
    id: 'img003',
    question: 'Which company developed Midjourney?',
    options: ['OpenAI', 'Stability AI', 'An independent research lab', 'Adobe'],
    correctIndex: 2,
    explanation: 'Midjourney is developed by Midjourney Inc., an independent research lab. It operates as a Discord bot and produces stunning artistic images.',
    difficulty: 'easy',
    category: 'image_ai',
  },
  {
    id: 'img004',
    question: 'What is ControlNet used for in image AI?',
    options: [
      'Controlling API rate limits for image generation',
      'Adding pose/edge/depth control to guide image generation',
      'A safety filter to block inappropriate content',
      'A tool to upscale low-resolution images',
    ],
    correctIndex: 1,
    explanation: 'ControlNet allows you to guide image generation using reference images — like a person\'s pose, an edge map, or depth map — giving much more precise control over the output.',
    difficulty: 'hard',
    category: 'image_ai',
  },
  {
    id: 'img005',
    question: 'Adobe Firefly is designed specifically to be safe for what type of use?',
    options: ['Personal use only', 'Academic research', 'Commercial use', 'Government projects'],
    correctIndex: 2,
    explanation: 'Adobe Firefly is trained on licensed stock images, making it safe for commercial use without IP concerns — a key differentiator from other image AI tools.',
    difficulty: 'easy',
    category: 'image_ai',
  },
  {
    id: 'img006',
    question: 'What is "img2img" in AI image generation?',
    options: [
      'Converting a JPEG to PNG format with AI',
      'Using an existing image as a starting point for generating a new one',
      'Splitting an image into two separate halves',
      'A technique to double the image resolution',
    ],
    correctIndex: 1,
    explanation: 'img2img (image-to-image) lets you use an existing image as the base and apply a text prompt to transform it, rather than generating from pure noise.',
    difficulty: 'medium',
    category: 'image_ai',
  },

  // ─── VIDEO AI ───────────────────────────────────────────────
  {
    id: 'vid001',
    question: 'Which company released Sora, the text-to-video AI model?',
    options: ['Google', 'Meta', 'OpenAI', 'Runway'],
    correctIndex: 2,
    explanation: 'Sora was released by OpenAI in 2024. It can generate up to 60-second photorealistic videos from text prompts, representing a major leap in video AI.',
    difficulty: 'easy',
    category: 'video_ai',
  },
  {
    id: 'vid002',
    question: 'Runway ML is best known for which type of AI capability?',
    options: ['Text generation', 'AI video editing and generation', 'Code completion', 'Voice cloning'],
    correctIndex: 1,
    explanation: 'Runway ML specializes in AI-powered video tools including Gen-3 Alpha for video generation, background removal, and professional video editing AI.',
    difficulty: 'easy',
    category: 'video_ai',
  },
  {
    id: 'vid003',
    question: 'What is ElevenLabs primarily used for?',
    options: ['Generating AI videos', 'Text-to-speech and voice cloning', 'AI image generation', 'Music composition'],
    correctIndex: 1,
    explanation: 'ElevenLabs is the leading AI voice platform — it offers ultra-realistic text-to-speech and voice cloning, used widely by content creators and businesses.',
    difficulty: 'easy',
    category: 'video_ai',
  },
  {
    id: 'vid004',
    question: 'What is HeyGen primarily used for?',
    options: [
      'AI code generation',
      'Creating AI avatar videos with lip-sync from text or audio',
      'Generating image slideshows from text',
      'Real-time video background removal',
    ],
    correctIndex: 1,
    explanation: 'HeyGen is an AI video platform that creates realistic avatar videos — you write a script and an AI-generated spokesperson delivers it with accurate lip-sync.',
    difficulty: 'medium',
    category: 'video_ai',
  },
  {
    id: 'vid005',
    question: 'Google\'s AI video generation model is called:',
    options: ['Gemini Video', 'Veo', 'Lumiere', 'VideoLM'],
    correctIndex: 1,
    explanation: 'Google\'s text-to-video model is called Veo (Veo 2 as of 2024). It competes with OpenAI\'s Sora and Runway\'s Gen-3 for high-quality video generation.',
    difficulty: 'hard',
    category: 'video_ai',
  },
  {
    id: 'vid006',
    question: 'Which open-source model is widely used for AI music generation?',
    options: ['AudioCraft by Meta', 'MusicGPT by OpenAI', 'HarmonyAI by Google', 'BeatNet by Stability AI'],
    correctIndex: 0,
    explanation: 'AudioCraft is Meta\'s open-source framework for AI music and audio generation. It includes MusicGen (music from text) and AudioGen (sound effects).',
    difficulty: 'hard',
    category: 'video_ai',
  },

  // ─── CODING AI ──────────────────────────────────────────────
  {
    id: 'code001',
    question: 'Which AI coding tool is described as "the AI-first code editor"?',
    options: ['GitHub Copilot', 'Cursor', 'Replit AI', 'Amazon CodeWhisperer'],
    correctIndex: 1,
    explanation: 'Cursor is an AI-first fork of VS Code that deeply integrates AI into the editing experience — you can chat with your codebase, apply diffs, and generate entire files.',
    difficulty: 'easy',
    category: 'coding_ai',
  },
  {
    id: 'code002',
    question: 'GitHub Copilot is primarily powered by which type of AI model?',
    options: ['Google Gemini', 'OpenAI Codex / GPT-4', 'Claude by Anthropic', 'Llama by Meta'],
    correctIndex: 1,
    explanation: 'GitHub Copilot was originally powered by OpenAI Codex and now uses GPT-4 level models. It\'s the most widely used AI coding assistant in the world.',
    difficulty: 'easy',
    category: 'coding_ai',
  },
  {
    id: 'code003',
    question: 'What is Devin AI known for?',
    options: [
      'Writing documentation automatically',
      'Being the first fully autonomous AI software engineer',
      'Generating UI designs from code',
      'A code review bot for GitHub pull requests',
    ],
    correctIndex: 1,
    explanation: 'Devin by Cognition AI is presented as the first fully autonomous AI software engineer — it can plan, write, debug, and deploy entire projects end-to-end.',
    difficulty: 'medium',
    category: 'coding_ai',
  },
  {
    id: 'code004',
    question: 'v0 by Vercel is used for:',
    options: [
      'Deploying Next.js apps to the cloud',
      'Generating React/Tailwind UI components from text prompts',
      'Monitoring web app performance',
      'AI-powered database query optimization',
    ],
    correctIndex: 1,
    explanation: 'v0.dev by Vercel generates React components using shadcn/ui and Tailwind CSS from text descriptions, dramatically speeding up frontend development.',
    difficulty: 'easy',
    category: 'coding_ai',
  },
  {
    id: 'code005',
    question: 'What is AlphaCode by DeepMind designed to do?',
    options: [
      'Generate AI images from code snippets',
      'Automatically deploy apps to Google Cloud',
      'Solve competitive programming problems',
      'Translate code between programming languages',
    ],
    correctIndex: 2,
    explanation: 'AlphaCode is DeepMind\'s AI system trained to solve competitive programming problems at near-human expert level, ranking in the top 54% of competitors.',
    difficulty: 'hard',
    category: 'coding_ai',
  },
  {
    id: 'code006',
    question: 'What is the purpose of a "system prompt" in AI coding assistants?',
    options: [
      'It starts the OS before the AI launches',
      'It sets instructions and context that guide the AI\'s behavior for the session',
      'It compiles code before sending it to the model',
      'It is the programming language the AI prefers to use',
    ],
    correctIndex: 1,
    explanation: 'A system prompt sets persistent instructions that shape the AI\'s behavior — like "You are a senior Python developer" — applied before any user message in the conversation.',
    difficulty: 'medium',
    category: 'coding_ai',
  },

  // ─── AI ETHICS ──────────────────────────────────────────────
  {
    id: 'eth001',
    question: 'The EU AI Act classifies AI systems into how many risk categories?',
    options: ['2', '3', '4', '5'],
    correctIndex: 2,
    explanation: 'The EU AI Act (2024) classifies AI into 4 risk levels: Unacceptable Risk (banned), High Risk (regulated), Limited Risk (transparency required), and Minimal Risk (free to use).',
    difficulty: 'hard',
    category: 'ethics',
  },
  {
    id: 'eth002',
    question: 'What is "AI alignment" concerned with?',
    options: [
      'Making AI models run faster on GPU clusters',
      'Ensuring AI systems act in accordance with human values and intentions',
      'Aligning multiple AI models to work on the same task',
      'The process of translating AI research papers',
    ],
    correctIndex: 1,
    explanation: 'AI alignment is the challenge of ensuring AI systems pursue goals that match human intentions — preventing scenarios where an AI optimizes for unintended objectives.',
    difficulty: 'medium',
    category: 'ethics',
  },
  {
    id: 'eth003',
    question: 'What does "RLHF" stand for?',
    options: [
      'Reinforcement Learning from Human Feedback',
      'Recursive Logic for Human-Facing Functions',
      'Randomized Learning from Historical Frameworks',
      'Reinforced Language with Heuristic Fine-tuning',
    ],
    correctIndex: 0,
    explanation: 'RLHF (Reinforcement Learning from Human Feedback) is the key technique used to align LLMs like ChatGPT — human raters rank outputs, and the model is trained to prefer higher-ranked responses.',
    difficulty: 'medium',
    category: 'ethics',
  },
  {
    id: 'eth004',
    question: 'Which organization published the "Constitutional AI" technique for safer AI?',
    options: ['OpenAI', 'DeepMind', 'Anthropic', 'Meta AI'],
    correctIndex: 2,
    explanation: 'Anthropic developed Constitutional AI (CAI) — a method where AI is guided by a set of principles (a "constitution") rather than relying entirely on human feedback for every response.',
    difficulty: 'hard',
    category: 'ethics',
  },
  {
    id: 'eth005',
    question: 'What is "AI hallucination"?',
    options: [
      'When AI creates visual art that looks surreal',
      'When AI confidently generates false or made-up information',
      'A visualization technique for neural network activations',
      'An AI dream-state during model training',
    ],
    correctIndex: 1,
    explanation: 'AI hallucination refers to when a language model confidently states incorrect or fabricated facts. It\'s a major challenge for real-world AI deployment and accuracy.',
    difficulty: 'easy',
    category: 'ethics',
  },
  {
    id: 'eth006',
    question: 'Which test measures whether a machine can exhibit human-like intelligence?',
    options: ['The Turing Test', 'The Imitation Game Score', 'The Lovelace Test', 'The Shannon Benchmark'],
    correctIndex: 0,
    explanation: 'The Turing Test, proposed by Alan Turing in 1950, measures whether a machine\'s conversation is indistinguishable from a human\'s to a third-party evaluator.',
    difficulty: 'easy',
    category: 'ethics',
  },

  // ─── MATH & ML ──────────────────────────────────────────────
  {
    id: 'math001',
    question: 'What does "gradient descent" do in neural network training?',
    options: [
      'Increases model parameters randomly to explore the solution space',
      'Updates model weights step by step to minimize the loss function',
      'Removes neurons with low activation from the network',
      'Sorts training data from easiest to hardest examples',
    ],
    correctIndex: 1,
    explanation: 'Gradient descent is the optimization algorithm that adjusts model weights in the direction that reduces the loss (error). It\'s the core training mechanism for neural networks.',
    difficulty: 'medium',
    category: 'math',
  },
  {
    id: 'math002',
    question: 'What is a "loss function" in machine learning?',
    options: [
      'A function that tracks the number of training epochs',
      'A mathematical function measuring how wrong the model\'s predictions are',
      'A function that removes outliers from training data',
      'The memory cost formula for loading a model',
    ],
    correctIndex: 1,
    explanation: 'The loss function measures the difference between the model\'s predictions and the actual correct answers. Training aims to minimize this value.',
    difficulty: 'easy',
    category: 'math',
  },
  {
    id: 'math003',
    question: 'What does the "softmax" function do in a neural network?',
    options: [
      'Converts negative values to positive ones',
      'Converts raw output scores into probabilities that sum to 1',
      'Softens the learning rate during training',
      'Compresses model weights for storage',
    ],
    correctIndex: 1,
    explanation: 'Softmax converts raw logit scores (any real numbers) into a probability distribution — all values become positive and sum to 1 — used in classification output layers.',
    difficulty: 'medium',
    category: 'math',
  },
  {
    id: 'math004',
    question: 'What is "overfitting" in machine learning?',
    options: [
      'Training a model with too many epochs',
      'A model that memorizes training data but fails on new data',
      'Fitting too many models in the same ensemble',
      'A GPU running out of VRAM during training',
    ],
    correctIndex: 1,
    explanation: 'Overfitting happens when a model learns the training data too precisely — including noise — and performs poorly on unseen data. It\'s like memorizing answers rather than understanding concepts.',
    difficulty: 'easy',
    category: 'math',
  },
  {
    id: 'math005',
    question: 'What does "ReLU" stand for in neural networks?',
    options: [
      'Recursive Linear Unit',
      'Rectified Linear Unit',
      'Regularized Learning Utility',
      'Recurrent Loss Update',
    ],
    correctIndex: 1,
    explanation: 'ReLU (Rectified Linear Unit) is an activation function: f(x) = max(0, x). It\'s the most commonly used activation in deep learning due to its simplicity and effectiveness.',
    difficulty: 'medium',
    category: 'math',
  },
  {
    id: 'math006',
    question: 'In transformers, what is the purpose of "positional encoding"?',
    options: [
      'To encode the position of the model in a data center',
      'To add information about the order of tokens since attention has no built-in order awareness',
      'To specify which GPU layer should process each token',
      'A technique to encode images as position coordinates',
    ],
    correctIndex: 1,
    explanation: 'Transformers process all tokens simultaneously (unlike RNNs), so positional encoding adds order information. Without it, "cat sat on mat" and "mat sat on cat" would look identical.',
    difficulty: 'hard',
    category: 'math',
  },

  // ─── PROMPTING ──────────────────────────────────────────────
  {
    id: 'prom001',
    question: 'What is "chain-of-thought" prompting?',
    options: [
      'Chaining multiple AI models together in a pipeline',
      'Asking the AI to reason step by step before giving a final answer',
      'A prompt technique that forces the AI to always use lists',
      'Linking related prompts together in a chat history',
    ],
    correctIndex: 1,
    explanation: 'Chain-of-thought (CoT) prompting — pioneered in the "Let\'s think step by step" paper — asks the model to show its reasoning, dramatically improving performance on complex tasks.',
    difficulty: 'medium',
    category: 'prompting',
  },
  {
    id: 'prom002',
    question: 'What is "few-shot prompting"?',
    options: [
      'Using only a few training examples when fine-tuning a model',
      'Providing the AI with example input-output pairs inside the prompt',
      'Limiting the model to a few tokens per response',
      'A technique to reduce hallucinations with strict temperature settings',
    ],
    correctIndex: 1,
    explanation: 'Few-shot prompting includes 2-5 example input/output pairs in your prompt to show the model the pattern you want. It dramatically improves accuracy without fine-tuning.',
    difficulty: 'easy',
    category: 'prompting',
  },
  {
    id: 'prom003',
    question: 'What does "temperature" control in LLM outputs?',
    options: [
      'The speed at which the model generates responses',
      'The GPU temperature during inference',
      'The randomness/creativity of the model\'s output',
      'The model\'s confidence threshold for refusing requests',
    ],
    correctIndex: 2,
    explanation: 'Temperature controls randomness: 0 = deterministic (always picks highest probability token), 1 = balanced, 2 = very creative/random. Low temp is better for factual tasks, high for creative writing.',
    difficulty: 'medium',
    category: 'prompting',
  },
  {
    id: 'prom004',
    question: 'What is "RAG" in the context of LLM applications?',
    options: [
      'Recursive Attention Generation',
      'Retrieval-Augmented Generation — fetching relevant documents before generating a response',
      'Randomized Autoregressive Grounding',
      'Real-time Agent Governance framework',
    ],
    correctIndex: 1,
    explanation: 'RAG (Retrieval-Augmented Generation) combines a knowledge base search with LLM generation — the model retrieves relevant documents first, then uses them to generate accurate, grounded responses.',
    difficulty: 'medium',
    category: 'prompting',
  },
  {
    id: 'prom005',
    question: 'What is a "system prompt" in an LLM API call?',
    options: [
      'The first message from the user in a conversation',
      'A hidden instruction that sets the AI\'s role, persona, and behavioral rules',
      'The model\'s internal reasoning before responding',
      'The server configuration file for the AI deployment',
    ],
    correctIndex: 1,
    explanation: 'The system prompt is a special instruction (invisible to end users) that shapes how the AI behaves — setting its persona, restrictions, format requirements, and knowledge context.',
    difficulty: 'easy',
    category: 'prompting',
  },
  {
    id: 'prom006',
    question: 'What does "top-p" (nucleus sampling) do?',
    options: [
      'Limits the response to only the top P paragraphs',
      'Selects the next token from the smallest set of tokens whose cumulative probability exceeds P',
      'A parameter that sets the maximum number of tokens in a response',
      'Filters the top P percent of training data during fine-tuning',
    ],
    correctIndex: 1,
    explanation: 'Top-p sampling only considers tokens whose combined probability reaches P (e.g., 0.9). Unlike top-k, it adapts the pool size — allowing more diversity when probabilities are spread out.',
    difficulty: 'hard',
    category: 'prompting',
  },
]

export function shuffleQuestions(questions: TriviaQuestion[], count = 10): TriviaQuestion[] {
  const shuffled = [...questions].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, shuffled.length))
}
