import { TriviaQuestion } from '@/types/game'

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'q001',
    question: 'Which architecture do GPT models use as their foundation?',
    options: ['RNN', 'Transformer', 'CNN', 'LSTM'],
    correctIndex: 1,
    explanation: 'GPT models use the Transformer architecture, introduced in "Attention Is All You Need" (2017) by Google Brain.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q002',
    question: 'What does "LLM" stand for in AI?',
    options: ['Large Language Model', 'Linear Learning Machine', 'Layered Logic Module', 'Lightweight Language Manager'],
    correctIndex: 0,
    explanation: 'LLM stands for Large Language Model — AI systems trained on massive text datasets like GPT-4, Claude, and Gemini.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q003',
    question: 'Which company created ChatGPT?',
    options: ['Google', 'Meta', 'OpenAI', 'Anthropic'],
    correctIndex: 2,
    explanation: 'OpenAI created ChatGPT, which launched in November 2022 and became one of the fastest-growing apps in history.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q004',
    question: 'What is "prompt engineering"?',
    options: [
      'Building physical AI hardware',
      'The art of crafting effective inputs to get better AI outputs',
      'Training AI models from scratch',
      'Debugging AI code errors',
    ],
    correctIndex: 1,
    explanation: 'Prompt engineering is the practice of designing and optimizing text prompts to guide AI models toward desired outputs.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q005',
    question: 'What is the "hallucination" problem in LLMs?',
    options: [
      'When AI sees visual patterns that aren\'t there',
      'When AI generates confidently stated but false information',
      'When AI models run too slowly',
      'When AI refuses to answer questions',
    ],
    correctIndex: 1,
    explanation: 'Hallucination refers to when LLMs generate plausible-sounding but factually incorrect information with apparent confidence.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q006',
    question: 'Which AI model was developed by Anthropic?',
    options: ['GPT-4', 'Gemini', 'Claude', 'Grok'],
    correctIndex: 2,
    explanation: 'Claude is Anthropic\'s AI assistant, known for its focus on safety and helpfulness. Anthropic was founded by former OpenAI researchers.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q007',
    question: 'What does "fine-tuning" an AI model mean?',
    options: [
      'Making an AI faster',
      'Adjusting hardware settings',
      'Further training a pre-trained model on specific data',
      'Removing bugs from AI code',
    ],
    correctIndex: 2,
    explanation: 'Fine-tuning involves taking a pre-trained model and training it further on a smaller, task-specific dataset to improve performance for that task.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q008',
    question: 'What year was the original Transformer paper "Attention Is All You Need" published?',
    options: ['2015', '2016', '2017', '2018'],
    correctIndex: 2,
    explanation: 'The landmark paper "Attention Is All You Need" was published in 2017 by researchers at Google Brain and Google Research.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 'q009',
    question: 'What is RAG in the context of AI?',
    options: [
      'Random Activation Generator',
      'Retrieval-Augmented Generation',
      'Recursive Attention Gradient',
      'Real-time AI Gateway',
    ],
    correctIndex: 1,
    explanation: 'RAG (Retrieval-Augmented Generation) combines language model generation with information retrieval to provide more accurate, up-to-date responses.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q010',
    question: 'Which AI tool generates images from text descriptions?',
    options: ['ChatGPT', 'DALL-E', 'Whisper', 'Copilot Code'],
    correctIndex: 1,
    explanation: 'DALL-E (by OpenAI) is a text-to-image AI model. Other popular image generators include Midjourney, Stable Diffusion, and Firefly.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q011',
    question: 'What is the "context window" of an LLM?',
    options: [
      'The visual interface of the AI',
      'The maximum amount of text the model can process at once',
      'The training data size',
      'The number of AI parameters',
    ],
    correctIndex: 1,
    explanation: 'The context window is the maximum number of tokens (roughly words/characters) an LLM can process in a single interaction — crucial for long documents.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q012',
    question: 'What does "GPU" stand for and why is it important for AI?',
    options: [
      'General Processing Unit — handles all computing',
      'Graphics Processing Unit — accelerates parallel computations for AI training',
      'Gigabyte Processing Unit — stores AI data',
      'Global Program Utility — manages AI software',
    ],
    correctIndex: 1,
    explanation: 'GPUs (Graphics Processing Units) are crucial for AI because they excel at parallel computation, dramatically speeding up matrix operations used in neural networks.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q013',
    question: 'Which company owns DeepMind?',
    options: ['Meta', 'Microsoft', 'Apple', 'Google/Alphabet'],
    correctIndex: 3,
    explanation: 'DeepMind was acquired by Google in 2014 and operates as part of Alphabet. They created AlphaGo, AlphaFold, and Gemini.',
    difficulty: 'medium',
    category: 'companies',
  },
  {
    id: 'q014',
    question: 'What is "tokenization" in NLP?',
    options: [
      'Encrypting AI responses',
      'Breaking text into smaller units (words/subwords) for processing',
      'Converting AI outputs to tokens for payment',
      'Storing AI models as blockchain tokens',
    ],
    correctIndex: 1,
    explanation: 'Tokenization is the process of splitting text into tokens (words, subwords, or characters) that the model can process numerically.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q015',
    question: 'What was the first AI to defeat a world champion at Go?',
    options: ['Deep Blue', 'Watson', 'AlphaGo', 'AlphaZero'],
    correctIndex: 2,
    explanation: 'AlphaGo by DeepMind defeated world Go champion Lee Sedol in 2016, marking a milestone in AI since Go has more board configurations than atoms in the universe.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 'q016',
    question: 'What is "RLHF" used for in training LLMs?',
    options: [
      'Reinforcement Learning from Human Feedback — aligning AI to human preferences',
      'Recursive Learning from Historical Files — training on old data',
      'Random Loss from Hidden Features — reducing model size',
      'Real-time Learning from Hardware Feedback — optimizing speed',
    ],
    correctIndex: 0,
    explanation: 'RLHF (Reinforcement Learning from Human Feedback) is the technique used to fine-tune models like ChatGPT to be helpful, harmless, and honest.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q017',
    question: 'What is Stable Diffusion?',
    options: [
      'A network stability protocol for AI servers',
      'An open-source text-to-image AI model',
      'A Microsoft AI coding assistant',
      'A method for stabilizing AI training',
    ],
    correctIndex: 1,
    explanation: 'Stable Diffusion is an open-source text-to-image model developed by Stability AI, notable for being free and runnable locally.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q018',
    question: 'What does "parameter" mean in the context of AI models?',
    options: [
      'The speed of the model',
      'The learnable weights in the neural network',
      'The input size limit',
      'The number of training examples',
    ],
    correctIndex: 1,
    explanation: 'Parameters are the learnable weights in a neural network. GPT-4 has ~1.8 trillion parameters. More parameters generally means more capability but also more compute.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q019',
    question: 'Which AI completed the Turing Test according to Alan Turing\'s original definition?',
    options: [
      'GPT-4',
      'ELIZA',
      'No AI has definitively passed it',
      'IBM Watson',
    ],
    correctIndex: 2,
    explanation: 'No AI has definitively and universally passed the Turing Test. While some AI in limited contexts has fooled judges, the test remains philosophically contested.',
    difficulty: 'hard',
    category: 'history',
  },
  {
    id: 'q020',
    question: 'What is "zero-shot learning" in AI?',
    options: [
      'Training a model with no data',
      'An AI performing tasks without any task-specific examples',
      'Achieving 0% error rate during training',
      'An AI that takes zero time to respond',
    ],
    correctIndex: 1,
    explanation: 'Zero-shot learning is when an AI performs a task it hasn\'t seen examples of, relying on its general knowledge and reasoning from its training.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q021',
    question: 'What is Microsoft Copilot?',
    options: [
      'A flight simulator AI',
      'Microsoft\'s AI assistant integrated into Microsoft 365 products',
      'An autonomous coding robot',
      'A cloud server management tool',
    ],
    correctIndex: 1,
    explanation: 'Microsoft Copilot is an AI assistant powered by OpenAI models, integrated into Microsoft 365 (Word, Excel, Teams) and Windows.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q022',
    question: 'What is the difference between AI and Machine Learning?',
    options: [
      'They are the same thing',
      'ML is a subset of AI that learns from data',
      'AI is a subset of ML',
      'ML only works with images, AI works with text',
    ],
    correctIndex: 1,
    explanation: 'AI is the broad field of making machines intelligent. Machine Learning is a subset of AI focused on systems that learn from data without explicit programming.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q023',
    question: 'What is "overfitting" in machine learning?',
    options: [
      'Training a model too long',
      'When a model learns training data too well and performs poorly on new data',
      'Having too many layers in a neural network',
      'Using too much GPU memory',
    ],
    correctIndex: 1,
    explanation: 'Overfitting occurs when a model memorizes training data rather than learning general patterns, causing poor performance on unseen data.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q024',
    question: 'Which company created the Gemini AI model?',
    options: ['OpenAI', 'Meta', 'Google', 'Mistral'],
    correctIndex: 2,
    explanation: 'Gemini is Google\'s flagship AI model, developed by Google DeepMind. It replaced the Bard chatbot and competes with GPT-4 and Claude.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q025',
    question: 'What does "multimodal AI" mean?',
    options: [
      'AI that runs on multiple servers',
      'AI that can process multiple types of data (text, images, audio)',
      'AI with multiple personalities',
      'AI that uses multiple programming languages',
    ],
    correctIndex: 1,
    explanation: 'Multimodal AI can understand and generate multiple modalities — like GPT-4V which processes both text and images, or Gemini Ultra which handles text, images, audio, and video.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q026',
    question: 'What is "attention mechanism" in transformers?',
    options: [
      'A way to make AI pay attention to user prompts',
      'A mechanism that lets models weigh the importance of different parts of input',
      'A monitoring system for AI outputs',
      'A technique to speed up model inference',
    ],
    correctIndex: 1,
    explanation: 'The attention mechanism allows transformers to consider how relevant each part of the input is to every other part, enabling better contextual understanding.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q027',
    question: 'Which open-source AI model family was released by Meta?',
    options: ['Claude', 'Gemma', 'Llama', 'Mistral'],
    correctIndex: 2,
    explanation: 'Meta released the Llama (Large Language Model Meta AI) family of open-source models, including Llama 2 and Llama 3, which can be run locally.',
    difficulty: 'easy',
    category: 'models',
  },
  {
    id: 'q028',
    question: 'What is "AI alignment"?',
    options: [
      'Making sure AI text is left-aligned',
      'Training AI to follow human values and intentions safely',
      'Synchronizing multiple AI systems',
      'Aligning AI training data with real-world distributions',
    ],
    correctIndex: 1,
    explanation: 'AI alignment is the challenge of ensuring AI systems behave in accordance with human values, intentions, and safety — a key focus area of Anthropic and OpenAI.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q029',
    question: 'What was IBM Watson famous for?',
    options: [
      'Generating images',
      'Writing code autonomously',
      'Defeating humans at Jeopardy! in 2011',
      'Creating the first chatbot',
    ],
    correctIndex: 2,
    explanation: 'IBM Watson famously defeated Jeopardy! champions Ken Jennings and Brad Rutter in 2011, showcasing AI\'s ability to understand natural language questions.',
    difficulty: 'medium',
    category: 'history',
  },
  {
    id: 'q030',
    question: 'What is "vector embedding" in AI?',
    options: [
      'Storing AI in a vector graphics format',
      'Converting text/data into numerical representations that capture meaning',
      'Embedding watermarks into AI outputs',
      'A technique for compressing AI models',
    ],
    correctIndex: 1,
    explanation: 'Vector embeddings are numerical representations of data (text, images) where similar items are closer in the vector space — crucial for semantic search and RAG.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q031',
    question: 'What AI tool helps developers write code?',
    options: ['DALL-E', 'GitHub Copilot', 'Whisper', 'Midjourney'],
    correctIndex: 1,
    explanation: 'GitHub Copilot, powered by OpenAI Codex, suggests code completions, functions, and entire blocks as you type in your editor.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q032',
    question: 'What is "diffusion" in AI image generation?',
    options: [
      'Distributing images across servers',
      'A process of gradually adding then removing noise to generate images',
      'Making images blurry for privacy',
      'A type of image compression algorithm',
    ],
    correctIndex: 1,
    explanation: 'Diffusion models learn to generate images by learning to reverse a process of gradually adding noise to images — the basis for Stable Diffusion and DALL-E 3.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q033',
    question: 'What is "AGI"?',
    options: [
      'Advanced Graphics Intelligence',
      'Artificial General Intelligence — AI that matches human-level reasoning across all tasks',
      'Automated Generation Interface',
      'Adaptive GPU Integration',
    ],
    correctIndex: 1,
    explanation: 'AGI (Artificial General Intelligence) refers to hypothetical AI that can perform any intellectual task a human can. Most experts believe we haven\'t achieved it yet.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q034',
    question: 'What is Hugging Face?',
    options: [
      'A social network for AI researchers',
      'A robot that simulates human emotions',
      'An open-source AI platform for sharing models, datasets, and demos',
      'A children\'s AI educational app',
    ],
    correctIndex: 2,
    explanation: 'Hugging Face is the "GitHub of AI" — a platform where researchers and developers share pre-trained models, datasets, and ML demos (Spaces).',
    difficulty: 'medium',
    category: 'tools',
  },
  {
    id: 'q035',
    question: 'What is "neural network" inspired by?',
    options: [
      'Computer circuit boards',
      'The human brain\'s structure of interconnected neurons',
      'Internet network topology',
      'Quantum physics',
    ],
    correctIndex: 1,
    explanation: 'Artificial neural networks are inspired by the biological neural networks in the human brain, using interconnected nodes that pass signals and learn.',
    difficulty: 'easy',
    category: 'concepts',
  },
  {
    id: 'q036',
    question: 'What milestone did AlphaFold achieve?',
    options: [
      'Defeated the world chess champion',
      'Solved the protein folding problem for nearly all known proteins',
      'Passed the Turing Test',
      'Wrote a novel indistinguishable from human writing',
    ],
    correctIndex: 1,
    explanation: 'AlphaFold by DeepMind predicted the 3D structure of nearly all 200 million known proteins with high accuracy, revolutionizing biology and drug discovery.',
    difficulty: 'hard',
    category: 'history',
  },
  {
    id: 'q037',
    question: 'What is "temperature" in LLM generation?',
    options: [
      'The heat generated by GPU during inference',
      'A parameter controlling randomness — higher = more creative, lower = more deterministic',
      'The processing speed of the model',
      'The length of generated text',
    ],
    correctIndex: 1,
    explanation: 'Temperature controls output randomness. Temperature 0 gives deterministic, repetitive outputs. Temperature 1+ gives more varied, creative (and sometimes incoherent) outputs.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q038',
    question: 'Which French AI company created the Mistral models?',
    options: ['BNP AI Labs', 'Mistral AI', 'Ariane Intelligence', 'EDF Tech'],
    correctIndex: 1,
    explanation: 'Mistral AI is a French startup that released highly capable open-source models (Mistral 7B, Mixtral 8x7B) competitive with much larger models.',
    difficulty: 'medium',
    category: 'companies',
  },
  {
    id: 'q039',
    question: 'What does "inference" mean in AI deployment?',
    options: [
      'Training the AI model',
      'Using a trained model to make predictions on new data',
      'Evaluating model accuracy',
      'Storing the model on servers',
    ],
    correctIndex: 1,
    explanation: 'Inference is when you use an already-trained model to generate outputs (predictions) from new inputs — distinct from training, which is the learning phase.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q040',
    question: 'What was the first publicly available chatbot?',
    options: ['Siri', 'ELIZA', 'Alexa', 'Cortana'],
    correctIndex: 1,
    explanation: 'ELIZA was created at MIT in 1966 by Joseph Weizenbaum. It simulated conversation using pattern matching and is considered one of the first chatbots.',
    difficulty: 'hard',
    category: 'history',
  },
  {
    id: 'q041',
    question: 'What is "few-shot learning"?',
    options: [
      'Training AI with very few GPU shots (iterations)',
      'Providing a small number of examples in the prompt to guide AI output',
      'A method that uses only 3-5 training samples total',
      'An efficient inference technique',
    ],
    correctIndex: 1,
    explanation: 'Few-shot learning involves giving the model a few examples in the prompt (e.g., 3-5 input-output pairs) to help it understand the desired output format.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q042',
    question: 'What is OpenRouter?',
    options: [
      'A router for open-source software networks',
      'An AI model from OpenAI',
      'A platform that provides unified access to many AI models via one API',
      'A tool for routing AI traffic across data centers',
    ],
    correctIndex: 2,
    explanation: 'OpenRouter is an API gateway that gives developers access to hundreds of AI models (GPT-4, Claude, Llama, etc.) through a single unified API.',
    difficulty: 'medium',
    category: 'tools',
  },
  {
    id: 'q043',
    question: 'What is "chain-of-thought prompting"?',
    options: [
      'Linking multiple chatbots together',
      'A technique where AI shows step-by-step reasoning before answering',
      'Chaining multiple API calls for complex tasks',
      'A blockchain-based AI verification method',
    ],
    correctIndex: 1,
    explanation: 'Chain-of-thought prompting (by Google Brain) encourages LLMs to reason step-by-step before giving a final answer, significantly improving performance on reasoning tasks.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q044',
    question: 'What is Midjourney?',
    options: [
      'A journey planning AI app',
      'An AI music generator',
      'An AI image generation tool accessible via Discord',
      'A mid-level AI chip for consumer GPUs',
    ],
    correctIndex: 2,
    explanation: 'Midjourney is a popular AI image generator known for high-quality, artistic outputs, accessible through a Discord bot interface.',
    difficulty: 'easy',
    category: 'tools',
  },
  {
    id: 'q045',
    question: 'What is "reinforcement learning"?',
    options: [
      'Strengthening neural network layers',
      'Training AI through rewards and penalties based on its actions',
      'Re-training models to fix errors',
      'Adding more data to strengthen model knowledge',
    ],
    correctIndex: 1,
    explanation: 'Reinforcement Learning trains AI agents by rewarding good actions and penalizing bad ones, used in game-playing AI, robotics, and RLHF for LLMs.',
    difficulty: 'medium',
    category: 'concepts',
  },
  {
    id: 'q046',
    question: 'What company created the Claude AI model?',
    options: ['OpenAI', 'Google', 'Meta', 'Anthropic'],
    correctIndex: 3,
    explanation: 'Claude is created by Anthropic, an AI safety company founded in 2021 by former OpenAI researchers including Dario Amodei and Daniela Amodei.',
    difficulty: 'easy',
    category: 'companies',
  },
  {
    id: 'q047',
    question: 'What is "Grok"?',
    options: [
      'A data analysis tool by Splunk',
      'An AI assistant created by xAI (Elon Musk\'s company)',
      'A German AI research institute',
      'An open-source LLM by Apache',
    ],
    correctIndex: 1,
    explanation: 'Grok is an AI assistant developed by xAI, Elon Musk\'s AI company, trained with access to real-time X (Twitter) data.',
    difficulty: 'medium',
    category: 'companies',
  },
  {
    id: 'q048',
    question: 'What is a "foundation model"?',
    options: [
      'The first AI model ever trained',
      'A large model trained on broad data that can be adapted to many tasks',
      'The base infrastructure running AI models',
      'An AI model for architecture/construction planning',
    ],
    correctIndex: 1,
    explanation: 'Foundation models are large AI models (like GPT-4, BERT) trained on vast datasets that serve as a base for fine-tuning on specific tasks — coined by Stanford researchers.',
    difficulty: 'hard',
    category: 'concepts',
  },
  {
    id: 'q049',
    question: 'What does "Whisper" do?',
    options: [
      'Generates whisper-quiet AI responses',
      'Converts speech to text (automatic speech recognition)',
      'Creates AI-generated audio/music',
      'A secret messaging AI tool',
    ],
    correctIndex: 1,
    explanation: 'Whisper is OpenAI\'s automatic speech recognition (ASR) model that transcribes and translates audio in 97 languages with high accuracy.',
    difficulty: 'medium',
    category: 'tools',
  },
  {
    id: 'q050',
    question: 'What is "model quantization" in AI?',
    options: [
      'Measuring model performance with quantum computers',
      'Reducing model size by using lower precision numbers, enabling local deployment',
      'Counting the number of parameters in a model',
      'A technique to split models across multiple GPUs',
    ],
    correctIndex: 1,
    explanation: 'Quantization reduces model precision (e.g., from 32-bit to 4-bit numbers), dramatically reducing file size and compute requirements — enabling local AI like llama.cpp.',
    difficulty: 'hard',
    category: 'concepts',
  },
]

export function shuffleQuestions(questions: TriviaQuestion[], count = 10): TriviaQuestion[] {
  const shuffled = [...questions].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, shuffled.length))
}
